name: Test

on:
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review, unlabeled]

  push:
    branches:
      - "develop"
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Run Unit Tests
      run: docker-compose -f "docker/test/docker-compose.yml" up --abort-on-container-exit --build
